# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
encoding: utf-8
highlighter: rouge
markdown: kramdown
disqus: 54fire
google_analytics: 54fire
title: 54fire'Blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 54fire

description: Do one thing,do it well!
author:
  name: 54fire
  email: 15123375513@163.com
  github: 54fire
  twitter: 
  pinterest:
  linkedin:
  bio: Do one thing,do it well!
  email_md5: 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH: https://54fire.github.io

plugins:
  - jekyll-paginate
